// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv"

const envName = process.env.NODE_ENV || "development"; 

const envFile = {
  development: "./src/config/.env.development",
  production: "./src/config/.env.production",
  test: "./src/config/.env.test",
}[envName];

dotenv.config({ path: envFile || "./src/config/.env" });

import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
